name: DevOps Workstation CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Syntax check playbook
        run: ansible-playbook --syntax-check setup.yml
